version: '2.1'
 
services:
  tcrum-db:
   container_name: tcrum-db
   build: ./BackEnd/db
   ports:
     - '5432:5432'
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   healthcheck:
     test: exit 0